### ISSUE TITLE
tvOS build fails with Carthage

### ISSUE THREAD

**Issue by ksmandersen** [duemunk/Async#65] opened 2015-11-07 19:15 UTC
Latest version ``1.6.3`` fails when installing through Carthage due to missing code signing for tvOS.

![screen shot 2015-11-07 at 20 12 51](https://cloud.githubusercontent.com/assets/178181/11016817/4a8b78fe-858c-11e5-831e-e21c9fb3ad40.png)

**Comment by duemunk** [comment] 2015-11-08 12:57
Has it worked before with Async to tvOS with Carthage? Never tested it.

**Comment by duemunk** [comment] 2015-11-08 12:59
Dupe of #59

**Closed by duemunk** 2015-11-08 12:59 UTC
Labels: duplicate
