### ISSUE TITLE
EXC_BAD_INSTRUCTION in Xcode 7 beta 6 when chaining

### ISSUE THREAD

**Issue by lexrus** [duemunk/Async#46] opened 2015-08-26 03:33 UTC
<img width="765" alt="screen shot 2015-08-26 at 11 10 41 am" src="https://cloud.githubusercontent.com/assets/219689/9485019/4ed7abe2-4be6-11e5-99b0-41913df162d1.png">

**Comment by Ewg777** [comment] 2015-08-27 09:34
Is there any solution?
```swift
Async.background {
  getData()
}.main {
  reload()
}
```
![Image of Yaktocat](http://i.imgur.com/F5zu0PY.png)

**Comment by duemunk** [comment] 2015-08-28 22:09
It seems like something has changed internally in GCD. I haven't been able to find a work around, so please file some radars :)

**Comment by duemunk** [comment] 2015-08-28 22:16
If you try to do the following in pure GCD (no Async at all) it still fails:
```swift
let queue = dispatch_get_main_queue()
let block1 = dispatch_block_create(DISPATCH_BLOCK_NO_QOS_CLASS, { print("1") })
let block2 = dispatch_block_create(DISPATCH_BLOCK_NO_QOS_CLASS, { print("2") })
dispatch_async(queue, block1)
dispatch_block_notify(block1, queue, block2)
```

**Comment by paulhyunkim** [comment] 2015-09-02 23:18
anyone find a solution to this?

**Comment by Ewg777** [comment] 2015-09-03 07:17
http://www.openradar.me/22437691 same issue but no progress

**Comment by akatkov7** [comment] 2015-09-03 15:11
It works in Xcode 7 beta 5 so you could use that while waiting for a more permanent solution.

**Comment by chenjsa** [comment] 2015-09-09 07:24
Here is my temporary solution in Xcode 7 beta 6
Async.background {
    //code
    Async.main {
        //code
    }
}

**Comment by DenisLaboureyras** [comment] 2015-09-09 21:52
I still have the problem with Xcode 7 GM. I think I will go with the temporary solution, even if I have plenty of code to change...

**Comment by thedamfr** [comment] 2015-09-15 08:53
![Giphy](http://media2.giphy.com/media/TNYy8aY7yateU/giphy.gif)

**Comment by johncoates** [comment] 2015-09-16 04:20
I ran into this, and not interested in changing all my chaining instances, so I added a work-around

Adapted code example from https://forums.developer.apple.com/message/50963

Made a class in Objective-C that executes all the code that crashes in Swift

```
@interface QDispatchBlock : NSObject

- (instancetype)initWithBlock:(dispatch_block_t)block;
- (void)dispatchAsyncToQueue:(dispatch_queue_t)queue;
- (void)notifyNextBlockOnCompletion:(QDispatchBlock *)nextBlock inQueue:(dispatch_queue_t)queue;
- (void)dispatchAfter:(dispatch_time_t)time inQueue:(dispatch_queue_t)queue;
- (void)wait:(dispatch_time_t)time;
- (void)cancel;

@end
@interface QDispatchBlock ()

@property (strong) dispatch_block_t block;

@end

@implementation QDispatchBlock

- (instancetype)initWithBlock:(dispatch_block_t)block {
    self = [super init];
    if (self != nil) {
        self->_block = dispatch_block_create(DISPATCH_BLOCK_INHERIT_QOS_CLASS, block);
    }
    return self;
}

- (void)dispatchAsyncToQueue:(dispatch_queue_t)queue {
    dispatch_async(dispatch_get_global_queue(qos_class_self(), 0), self.block);
}

- (void)notifyNextBlockOnCompletion:(QDispatchBlock *)nextBlock inQueue:(dispatch_queue_t)queue {
    dispatch_block_notify(self.block, queue, nextBlock.block);
}

- (void)dispatchAfter:(dispatch_time_t)time inQueue:(dispatch_queue_t)queue {
    dispatch_after(time, queue, self.block);
}

- (void)wait:(dispatch_time_t)time {
    dispatch_block_wait(self.block, time);
}

- (void)cancel {
    dispatch_block_cancel(self.block);
}
@end
```

**Comment by harlanhaskins** [comment] 2015-09-16 14:34
@johncoates Would you mind forking Async and putting all that code there?

**Comment by johncoates** [comment] 2015-09-16 19:15
@harlanhaskins Sure, I forked it here https://github.com/johncoates/Async

**Comment by harlanhaskins** [comment] 2015-09-16 20:45
It looks like

```objc
- (void)dispatchAsyncToQueue:(dispatch_queue_t)queue {
    dispatch_async(dispatch_get_global_queue(qos_class_self(), 0), self.block);
}
```

should be

```objc
- (void)dispatchAsyncToQueue:(dispatch_queue_t)queue {
    dispatch_async(queue, self.block);
}
```

Because otherwise it just ignores the argument...

**Comment by JohnCoates** [comment] 2015-09-16 20:55
@harlanhaskins You're right, I didn't even think to read through that code to be honest, I just copied it from the code example and figured it was correct since an Apple employee had written it haha.  It's been corrected now

**Comment by duemunk** [comment] 2015-09-18 09:27
Awesome to see that you've managed to found a solution to this problem. I might want to include the fix in this repo, but the main purpose of **Async** is to simplify `GCD`.

The only solution as I see it right now, is to bump the minimum requirements to iOS 9.1 if and when it gets fixed.

**Comment by thedamfr** [comment] 2015-09-21 12:36
So if I want to release today on 9.0 I have to get rid of Async ?

**Comment by thedamfr** [comment] 2015-09-21 13:05
@duemunk Look at https://github.com/JohnCoates/Async/pull/1
I updated @JohnCoates .podspec and it friction-less for the developer to integrate the bugfix.
What do you think ?

**Comment by christianlanz** [comment] 2015-09-22 15:30
@duemunk A library with bugs make people less likely to use it :D

**Comment by duemunk** [comment] 2015-09-22 16:21
@christianlanz I know. But I kinda have a life as well :)

**Comment by limoges** [comment] 2015-09-24 19:30
@duemunk In my opinion, the fix should be merged into the main branch. The library should support iOS 9 and Xcode 7. Otherwise people will flee the project because late dependencies are a deal-breaker.

@JohnCoates  Thanks for doing the work. You are saving me some time.

**Comment by lexrus** [comment] 2015-09-25 04:17
I agree with @limoges . But it's true the owner has the right to decline any unwanted feature or workaround. We may temporarily use @JohnCoates 's fork before an official fix by Apple.

**Comment by DivineDominion** [comment] 2015-09-28 14:39
Affects OS X 10.11 and Xcode 7, too, in case no-one's aware of this. Weird thing.

**Comment by duemunk** [comment] 2015-09-28 15:28
I'm trying to look into this. Also newer versions of Swift might fix it and still work on iOS 9. I'll probably include the fix, but hope to remove it as fast as possible.

**Comment by timshadel** [comment] 2015-09-29 19:33
Any chance this is fixed in Xcode 7.0.1 released today?

**Comment by duemunk** [comment] 2015-10-02 16:25
I just tested in Xcode 7.1 which has Swift 2.1. It works!

The issue is mentioned in the release notes and points to http://www.openradar.me/22432170, which @Ewg777 also mentioned.

Since the fix is just down the road, I will not merge this temporary fix. Those who need Swift 2.0 support will have to use a fork like https://github.com/JohnCoates/Async.

**Comment by duemunk** [comment] 2015-10-02 17:50
I've made a new branch https://github.com/duemunk/Async/tree/feature/Swift_2.1. I'll probably merge soon, but if someone has any feedback—please let me know!

Again, thanks for all the work. It's nice to see the project thriving like this, despite me not being super speedy to respond :)

**Comment by lexrus** [comment] 2015-10-23 03:57
Xcode 7.1 was released yesterday. Can we close this issue?

**Comment by duemunk** [comment] 2015-10-23 11:00
Done. Thanks for all the great help peeps!

**Closed by duemunk** 2015-10-23 11:00 UTC
Labels: bug, wontfix

**Comment by esttorhe** [comment] 2015-10-29 14:19
Any chance to bring back the swift2.0 brach?

We have a project that's depending on it and can't adopt 2.1 just yet due to all the other dependencies not supporting it.

Maybe bring it back to let me fork it and then nuke it again until all our dependencies support 2.1?

Thanks for the great framework BTW

**Comment by duemunk** [comment] 2015-10-29 23:40
For Swift 2.0, you should use the fork https://github.com/JohnCoates/Async.

**Comment by esttorhe** [comment] 2015-10-29 23:41
:ok_hand: will do. thanks
